title: Stronger Self Fitness and Health
email: your-email@example.com
description: >-
  Stronger Self Fitness and Health – Guiding you to your strongest self.
baseurl: "" # leave empty for GitHub Pages
url: "https://digitalsparkhq.github.io/grinderspencer-site/"
